export const authTypes={
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGIN_FAIL:"LOGIN_FAIL",
  LOGIN_REQUEST:"LOGIN_REQUEST",
  LOAD_PROFILE:"LOAD_PROFILE",
  LOG_OUT:"LOG_OUT"

}

export const homeVideosTypes={
  HOME_VIDEOS_REQUEST:"HOME_VIDEOS_REQUEST",
  HOME_VIDEOS_SUCCESS:"HOME_VIDEOS_SUCCESS",
  HOME_VIDEOS_ERROR:"HOME_VIDEOS_ERROR",
  ADD_MORE_VIDEOS:"ADD_MORE_VIDEOS"
}
export const selectedVideos={
  GET_VIDEO_DATA_REQ:"GET_VIDEO_DATA_REQ",
  GET_VIDEO_DATA_SUCCESS:"GET_VIDEO_DATA_SUCCESS",
  GET_VIDEO_DATA_ERROR:"GET_VIDEO_DATA_ERROR"
}

export const getChannelDetails={
  GET_CHANNEL_DETAILS_REQ:"GET_CHANNEL_DETAILS_REQ",
  GET_CHANNEL_DETAILS_SUCCESS:"GET_CHANNEL_DETAILS_SUCCESS",
  GET_CHANNEL_DETAILS_FAIL:"GET_CHANNEL_DETAILS_FAIL"
}
export const getSubscriptionStatusTypes="getSubscriptionStatusTypes"
export const getCommentsTypes={
  GET_COMMENTS_REQUEST:"GET_COMMENTS_REQUEST",
  GET_COMMENTS_SUCCESS:"GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAIL:"GET_COMMENTS_FAIL"
}

export const postCommentsTypes={
  POST_COMMENTS_SUCCESS:"POST_COMMENTS_SUCCESS",
  POST_COMMENTS_FAIL:"POST_COMMENTS_FAIL"
}
export const relatedVideosTypes={
  GET_RELATED_VIDEOS_REQUEST:"GET_RELATED_VIDEOS_REQUEST",
  GET_RELATED_VIDEOS_SUCCESS:"GET_RELATED_VIDEOS_SUCCESS",
  GET_RELATED_VIDEOS_ADD_MORE:"GET_RELATED_VIDEOS_ADD_MORE",
  GET_RELATED_VIDEOS_FAIL:"GET_RELATED_VIDEOS_FAIL"
}
export const getSubscriptionChannelTypes={
  GET_SUBSCRIPTION_CHANNEL_REQUEST:"GET_SUBSCRIPTION_CHANNEL_REQUEST",
  GET_SUBSCRIPTION_CHANNEL_SUCCESS:"GET_SUBSCRIPTION_CHANNEL_SUCCESS",
  GET_SUBSCRIPTION_CHANNEL_FAIL:"GET_SUBSCRIPTION_CHANNEL_FAIL"
}
